#! /bin/sh

sxhkd &

bspc monitor -d SYS IDE WEB IRC DISC MUSIC VIDEO 

bspc config border_width         2
bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt    state=floating
bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center ~/Pictures/ExplodeHead.jpg
compton &
mpd &
panel &
